version: '3.3'
services:
  postgres:
    image: postgres:12.18-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwertypoikjh1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=btc